<?php

function trip_utils_node_view($node, $view_mode, $langcode) {
  unset($node->content['links']['comment']);
  return $node;
}

function trip_utils_views_api() {
  return array(
    'api' => 3, 
    'template path' => drupal_get_path('module', 'trip_utils')
  );
}

/**
 * Implementation of hook_init().
 */
function trip_utils_init() {
  
  drupal_add_js(drupal_get_path('module', 'trip_utils') . '/trip_utils.js');
  drupal_add_css(drupal_get_path('module', 'trip_utils') . '/trip_utils.css');

}

function trip_utils_node_insert($node, $arg = 0) {
  db_merge('node')
    ->key(array('nid' => $node->nid))
    ->fields(array(
       'trip_last_comment' => $node->created,
     ))
    ->execute();
}


function trip_utils_comment_insert($comment) {
  db_merge('node')
  ->key(array('nid' => $comment->nid))
  ->fields(array(
     'trip_last_comment' => $comment->changed,
   ))
  ->execute();
}


function trip_utils_process_node(&$variables) {
  
   
  $node = $variables['node'];
   
  $variables['submitted'] =  t('!username on !datetime.',
    array(
    '!username' => theme('username', array('account' => $node)),
    '!datetime' => format_date($node->changed, 'custom', 'j. M Y H:i'),
  ));

}

function trip_utils_process_comment(&$variables) {
  
  $variables['title'] = NULL;
  
  $comment = $variables['comment'];
   
  $variables['submitted'] = t('!username on !datetime.',
    array(
    '!username' => theme('username', array('account' => $comment)),
    '!datetime' => l(format_date($comment->changed, 'custom', 'j. M Y H:i'), 'node/' . $comment->nid, array('fragment' => 'comment-' . $comment->cid)),
  ));

}
